### PR TITLE
Removal of all files, to start fresh

### PR DESCRIPTION
**Pull request by perlchild**

### CODE REVIEW

**Comment by perlchild** [comment]
For extra transparency I'm making this a PR

**Comment by x70b1** [comment]
Aaaand it's gone.

**Comment by majormoses** [comment]
Sorry I did not review this in time. This was a bit of a cowboy and I think we should try to bit more disciplined. Here are some thoughts as to what I imagine we would do next time in a similar scenerio:
- why bother wiping what we currently have until we have something functional?
- why not checkout a fresh branch rather than deleting all the files? https://gist.github.com/j8/8997663
- we should have created a legacy or similar branch and updated `README.md` to point anyone who was using it to the right branch to keep working.

Oh well, tbh it might have been the best to nuke and pave in this manner with such an old project with lots of bitrot. I tend to prefer to follow the mantra of break no one where possible, when that is not possible provide a migration path and attempt to save users even when they are doing things that are not recommended such as deploying from master on an open source project.

**Comment by russellballestrini** [comment]
No worries, I recovered my Fork here: https://github.com/russellballestrini/sensu-salt which I have updated my [blog post](https://russell.ballestrini.net/sensu-salt/) to link to. Thanks for all the fish.

**Pull request merged**
